@extends('layouts.admin')
@section('title', 'Website Settings')
@section('heading', 'Website Settings')
@section('eyebrow', 'Public site controls')
@section('content')
<form action="{{ route('admin.settings.update') }}" method="POST" class="space-y-7">@csrf @method('PUT')
    <section data-admin-reveal class="admin-panel"><div class="admin-panel-heading"><div><p class="admin-kicker">Company information</p><h2 class="admin-title">Contact details</h2></div></div><div class="mt-7 grid gap-5 md:grid-cols-2">
        @foreach([['company_name','Company name'],['email','Public email'],['phone_primary','Primary phone'],['phone_secondary','Secondary phone'],['address','Postal address']] as $field)<label class="{{ $field[0] === 'address' ? 'md:col-span-2' : '' }}"><span class="admin-label">{{ $field[1] }}</span><input name="{{ $field[0] }}" value="{{ old($field[0], $settings[$field[0]]) }}" class="admin-input"></label>@endforeach
    </div></section>
    <section data-admin-reveal class="admin-panel"><p class="admin-kicker">Homepage facts</p><h2 class="admin-title mt-2">Capability figures</h2><div class="mt-7 grid gap-5 md:grid-cols-2"><label><span class="admin-label">Drilling capacity (metres)</span><input type="number" name="drilling_capacity" value="{{ old('drilling_capacity', $settings['drilling_capacity']) }}" class="admin-input"></label><label><span class="admin-label">Deployable teams</span><input type="number" name="deployable_teams" value="{{ old('deployable_teams', $settings['deployable_teams']) }}" class="admin-input"></label></div></section>
    <section data-admin-reveal class="admin-panel"><p class="admin-kicker">Navigation links</p><h2 class="admin-title mt-2">Social media</h2><div class="mt-7 grid gap-5 md:grid-cols-2">@foreach(['facebook_url'=>'Facebook URL','twitter_url'=>'Twitter / X URL','google_url'=>'Google URL','instagram_url'=>'Instagram URL','pinterest_url'=>'Pinterest URL'] as $key=>$label)<label><span class="admin-label">{{ $label }}</span><input name="{{ $key }}" value="{{ old($key, $settings[$key]) }}" class="admin-input"></label>@endforeach</div></section>
    <section data-admin-reveal class="admin-panel"><p class="admin-kicker">System controls</p><h2 class="admin-title mt-2">Maintenance and privacy</h2><div class="mt-7 grid gap-6 md:grid-cols-2"><label><span class="admin-label">Analytics retention (days)</span><input type="number" name="analytics_retention_days" value="{{ old('analytics_retention_days', $settings['analytics_retention_days']) }}" class="admin-input"><small class="mt-2 block text-xs text-slate-500">Old privacy-friendly analytics are deleted automatically.</small></label><label class="flex items-start gap-4 border border-slate-200 p-5"><input type="checkbox" name="maintenance_enabled" value="1" @checked($settings['maintenance_enabled'] === '1') class="mt-1 h-5 w-5 accent-[#FFA729]"><span><strong class="block text-sm text-[#081a43]">Maintenance mode</strong><small class="mt-1 block leading-5 text-slate-500">Temporarily hide the visitor website while administrators retain access.</small></span></label></div></section>
    <div class="sticky bottom-4 flex justify-end"><button class="admin-primary-btn shadow-xl"><i class="fas fa-floppy-disk"></i>Save website settings</button></div>
</form>
@endsection
