@extends('layouts.admin')
@section('title', 'Administrators')
@section('heading', 'Administrators')
@section('eyebrow', 'Access management')
@section('content')
<section class="grid gap-7 xl:grid-cols-[0.75fr_1.25fr]">
    <form data-admin-reveal action="{{ route('admin.administrators.store') }}" method="POST" class="admin-panel self-start">@csrf
        <p class="admin-kicker">Invite securely</p><h2 class="admin-title mt-2">Create administrator</h2>
        <div class="mt-6 space-y-5"><label class="block"><span class="admin-label">Full name</span><input name="name" class="admin-input" required></label><label class="block"><span class="admin-label">Email</span><input type="email" name="email" class="admin-input" required></label><label class="block"><span class="admin-label">Role</span><select name="role" class="admin-input"><option value="editor">Editor</option><option value="owner">Owner</option></select></label><label class="block"><span class="admin-label">Temporary password</span><input type="password" name="password" class="admin-input" required></label><label class="block"><span class="admin-label">Confirm password</span><input type="password" name="password_confirmation" class="admin-input" required></label><button class="admin-primary-btn w-full"><i class="fas fa-user-plus"></i>Create administrator</button></div>
    </form>
    <div class="space-y-5">
    @foreach($admins as $admin)<form data-admin-reveal action="{{ route('admin.administrators.update', $admin) }}" method="POST" class="admin-panel">@csrf @method('PUT')
        <div class="flex items-center gap-4 border-b border-slate-100 pb-5"><span class="grid h-12 w-12 place-items-center bg-[#081a43] text-lg font-black text-white">{{ strtoupper(substr($admin->name,0,1)) }}</span><div class="min-w-0 flex-1"><h2 class="truncate text-lg font-black text-[#081a43]">{{ $admin->name }}</h2><p class="truncate text-sm text-slate-500">{{ $admin->email }}</p></div><span class="admin-status {{ $admin->is_active ? 'admin-status-contacted' : 'admin-status-closed' }}">{{ $admin->is_active ? 'active' : 'disabled' }}</span></div>
        <div class="mt-6 grid gap-4 sm:grid-cols-2"><label><span class="admin-label">Name</span><input name="name" value="{{ $admin->name }}" class="admin-input"></label><label><span class="admin-label">Email</span><input name="email" type="email" value="{{ $admin->email }}" class="admin-input"></label><label><span class="admin-label">Role</span><select name="role" class="admin-input" @disabled($admin->is(auth('admin')->user()))><option value="editor" @selected($admin->role==='editor')>Editor</option><option value="owner" @selected($admin->role==='owner')>Owner</option></select>@if($admin->is(auth('admin')->user()))<input type="hidden" name="role" value="owner">@endif</label><label class="flex items-center gap-3 self-end border border-slate-200 px-4 py-3.5"><input type="checkbox" name="is_active" value="1" @checked($admin->is_active) @disabled($admin->is(auth('admin')->user())) class="h-5 w-5 accent-[#FFA729]"><span class="text-sm font-bold text-[#081a43]">Account active</span></label><label><span class="admin-label">New password (optional)</span><input type="password" name="password" class="admin-input"></label><label><span class="admin-label">Confirm new password</span><input type="password" name="password_confirmation" class="admin-input"></label></div>
        <div class="mt-5 flex flex-wrap items-center justify-between gap-4"><p class="text-xs text-slate-500">Last login: {{ $admin->last_login_at?->diffForHumans() ?? 'Never' }}</p><div class="flex gap-4"><button class="admin-secondary-btn"><i class="fas fa-floppy-disk"></i>Save</button>@if(!$admin->is(auth('admin')->user()))<button form="delete-admin-{{ $admin->id }}" class="text-sm font-black uppercase text-red-600" onclick="return confirm('Delete this administrator?')">Delete</button>@endif</div></div>
    </form>@if(!$admin->is(auth('admin')->user()))<form id="delete-admin-{{ $admin->id }}" action="{{ route('admin.administrators.destroy', $admin) }}" method="POST">@csrf @method('DELETE')</form>@endif @endforeach
    </div>
</section>
@endsection
